/**
 * @fileoverview
 * @author Taketoshi Aono
 */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HAS_TYPED_ARRAY = typeof Uint16Array === 'function';
exports.BUFFER_SIZE_MULTIPLER = exports.HAS_TYPED_ARRAY ? 2 : 1;
var BuiltinElementValue;
(function (BuiltinElementValue) {
    BuiltinElementValue[BuiltinElementValue["CHILDREN"] = 2] = "CHILDREN";
})(BuiltinElementValue = exports.BuiltinElementValue || (exports.BuiltinElementValue = {}));
var FuelBuiltinElements;
(function (FuelBuiltinElements) {
    FuelBuiltinElements[FuelBuiltinElements["A"] = 1] = "A";
    FuelBuiltinElements[FuelBuiltinElements["ABBR"] = 2] = "ABBR";
    FuelBuiltinElements[FuelBuiltinElements["ADDRESS"] = 3] = "ADDRESS";
    FuelBuiltinElements[FuelBuiltinElements["AREA"] = 4] = "AREA";
    FuelBuiltinElements[FuelBuiltinElements["ARTICLE"] = 5] = "ARTICLE";
    FuelBuiltinElements[FuelBuiltinElements["ASIDE"] = 6] = "ASIDE";
    FuelBuiltinElements[FuelBuiltinElements["AUDIO"] = 7] = "AUDIO";
    FuelBuiltinElements[FuelBuiltinElements["BASE"] = 8] = "BASE";
    FuelBuiltinElements[FuelBuiltinElements["BDI"] = 9] = "BDI";
    FuelBuiltinElements[FuelBuiltinElements["BDO"] = 10] = "BDO";
    FuelBuiltinElements[FuelBuiltinElements["BIG"] = 11] = "BIG";
    FuelBuiltinElements[FuelBuiltinElements["BLOCKQUOTE"] = 12] = "BLOCKQUOTE";
    FuelBuiltinElements[FuelBuiltinElements["BODY"] = 13] = "BODY";
    FuelBuiltinElements[FuelBuiltinElements["BR"] = 14] = "BR";
    FuelBuiltinElements[FuelBuiltinElements["BUTTON"] = 15] = "BUTTON";
    FuelBuiltinElements[FuelBuiltinElements["CANVAS"] = 16] = "CANVAS";
    FuelBuiltinElements[FuelBuiltinElements["CAPTION"] = 17] = "CAPTION";
    FuelBuiltinElements[FuelBuiltinElements["CITE"] = 18] = "CITE";
    FuelBuiltinElements[FuelBuiltinElements["CODE"] = 19] = "CODE";
    FuelBuiltinElements[FuelBuiltinElements["COL"] = 20] = "COL";
    FuelBuiltinElements[FuelBuiltinElements["COLGROUP"] = 21] = "COLGROUP";
    FuelBuiltinElements[FuelBuiltinElements["DATA"] = 22] = "DATA";
    FuelBuiltinElements[FuelBuiltinElements["DATALIST"] = 23] = "DATALIST";
    FuelBuiltinElements[FuelBuiltinElements["DD"] = 24] = "DD";
    FuelBuiltinElements[FuelBuiltinElements["DEL"] = 25] = "DEL";
    FuelBuiltinElements[FuelBuiltinElements["DETAILS"] = 26] = "DETAILS";
    FuelBuiltinElements[FuelBuiltinElements["DFN"] = 27] = "DFN";
    FuelBuiltinElements[FuelBuiltinElements["DIALOG"] = 28] = "DIALOG";
    FuelBuiltinElements[FuelBuiltinElements["DIV"] = 29] = "DIV";
    FuelBuiltinElements[FuelBuiltinElements["DL"] = 30] = "DL";
    FuelBuiltinElements[FuelBuiltinElements["DT"] = 31] = "DT";
    FuelBuiltinElements[FuelBuiltinElements["EM"] = 32] = "EM";
    FuelBuiltinElements[FuelBuiltinElements["EMBED"] = 33] = "EMBED";
    FuelBuiltinElements[FuelBuiltinElements["FIELDSET"] = 34] = "FIELDSET";
    FuelBuiltinElements[FuelBuiltinElements["FIGCAPTION"] = 35] = "FIGCAPTION";
    FuelBuiltinElements[FuelBuiltinElements["FIGURE"] = 36] = "FIGURE";
    FuelBuiltinElements[FuelBuiltinElements["FOOTER"] = 37] = "FOOTER";
    FuelBuiltinElements[FuelBuiltinElements["FORM"] = 38] = "FORM";
    FuelBuiltinElements[FuelBuiltinElements["H1"] = 39] = "H1";
    FuelBuiltinElements[FuelBuiltinElements["H2"] = 40] = "H2";
    FuelBuiltinElements[FuelBuiltinElements["H3"] = 41] = "H3";
    FuelBuiltinElements[FuelBuiltinElements["H4"] = 42] = "H4";
    FuelBuiltinElements[FuelBuiltinElements["H5"] = 43] = "H5";
    FuelBuiltinElements[FuelBuiltinElements["H6"] = 44] = "H6";
    FuelBuiltinElements[FuelBuiltinElements["HEAD"] = 45] = "HEAD";
    FuelBuiltinElements[FuelBuiltinElements["HEADER"] = 46] = "HEADER";
    FuelBuiltinElements[FuelBuiltinElements["HGROUP"] = 47] = "HGROUP";
    FuelBuiltinElements[FuelBuiltinElements["HR"] = 48] = "HR";
    FuelBuiltinElements[FuelBuiltinElements["HTML"] = 49] = "HTML";
    FuelBuiltinElements[FuelBuiltinElements["I"] = 50] = "I";
    FuelBuiltinElements[FuelBuiltinElements["IFRAME"] = 51] = "IFRAME";
    FuelBuiltinElements[FuelBuiltinElements["IMG"] = 52] = "IMG";
    FuelBuiltinElements[FuelBuiltinElements["INPUT"] = 53] = "INPUT";
    FuelBuiltinElements[FuelBuiltinElements["INS"] = 54] = "INS";
    FuelBuiltinElements[FuelBuiltinElements["KBD"] = 55] = "KBD";
    FuelBuiltinElements[FuelBuiltinElements["KEYGEN"] = 56] = "KEYGEN";
    FuelBuiltinElements[FuelBuiltinElements["LABEL"] = 57] = "LABEL";
    FuelBuiltinElements[FuelBuiltinElements["LEGEND"] = 58] = "LEGEND";
    FuelBuiltinElements[FuelBuiltinElements["LI"] = 59] = "LI";
    FuelBuiltinElements[FuelBuiltinElements["LINK"] = 60] = "LINK";
    FuelBuiltinElements[FuelBuiltinElements["MAIN"] = 61] = "MAIN";
    FuelBuiltinElements[FuelBuiltinElements["MAP"] = 62] = "MAP";
    FuelBuiltinElements[FuelBuiltinElements["MARK"] = 63] = "MARK";
    FuelBuiltinElements[FuelBuiltinElements["MENU"] = 64] = "MENU";
    FuelBuiltinElements[FuelBuiltinElements["MENUITEM"] = 65] = "MENUITEM";
    FuelBuiltinElements[FuelBuiltinElements["META"] = 66] = "META";
    FuelBuiltinElements[FuelBuiltinElements["METER"] = 67] = "METER";
    FuelBuiltinElements[FuelBuiltinElements["NAV"] = 68] = "NAV";
    FuelBuiltinElements[FuelBuiltinElements["NOSCRIPT"] = 69] = "NOSCRIPT";
    FuelBuiltinElements[FuelBuiltinElements["OBJECT"] = 70] = "OBJECT";
    FuelBuiltinElements[FuelBuiltinElements["OL"] = 71] = "OL";
    FuelBuiltinElements[FuelBuiltinElements["OPTGROUP"] = 72] = "OPTGROUP";
    FuelBuiltinElements[FuelBuiltinElements["OPTION"] = 73] = "OPTION";
    FuelBuiltinElements[FuelBuiltinElements["OUTPUT"] = 74] = "OUTPUT";
    FuelBuiltinElements[FuelBuiltinElements["P"] = 75] = "P";
    FuelBuiltinElements[FuelBuiltinElements["PARAM"] = 76] = "PARAM";
    FuelBuiltinElements[FuelBuiltinElements["PICTURE"] = 77] = "PICTURE";
    FuelBuiltinElements[FuelBuiltinElements["PRE"] = 78] = "PRE";
    FuelBuiltinElements[FuelBuiltinElements["PROGRESS"] = 79] = "PROGRESS";
    FuelBuiltinElements[FuelBuiltinElements["Q"] = 80] = "Q";
    FuelBuiltinElements[FuelBuiltinElements["RP"] = 81] = "RP";
    FuelBuiltinElements[FuelBuiltinElements["RT"] = 82] = "RT";
    FuelBuiltinElements[FuelBuiltinElements["RUBY"] = 83] = "RUBY";
    FuelBuiltinElements[FuelBuiltinElements["S"] = 84] = "S";
    FuelBuiltinElements[FuelBuiltinElements["SAMP"] = 85] = "SAMP";
    FuelBuiltinElements[FuelBuiltinElements["SCRIPT"] = 86] = "SCRIPT";
    FuelBuiltinElements[FuelBuiltinElements["SECTION"] = 87] = "SECTION";
    FuelBuiltinElements[FuelBuiltinElements["SELECT"] = 88] = "SELECT";
    FuelBuiltinElements[FuelBuiltinElements["SMALL"] = 89] = "SMALL";
    FuelBuiltinElements[FuelBuiltinElements["SOURCE"] = 90] = "SOURCE";
    FuelBuiltinElements[FuelBuiltinElements["SPAN"] = 91] = "SPAN";
    FuelBuiltinElements[FuelBuiltinElements["STRONG"] = 92] = "STRONG";
    FuelBuiltinElements[FuelBuiltinElements["STYLE"] = 93] = "STYLE";
    FuelBuiltinElements[FuelBuiltinElements["SUB"] = 94] = "SUB";
    FuelBuiltinElements[FuelBuiltinElements["SUMMARY"] = 95] = "SUMMARY";
    FuelBuiltinElements[FuelBuiltinElements["SUP"] = 96] = "SUP";
    FuelBuiltinElements[FuelBuiltinElements["TABLE"] = 97] = "TABLE";
    FuelBuiltinElements[FuelBuiltinElements["TBODY"] = 98] = "TBODY";
    FuelBuiltinElements[FuelBuiltinElements["TD"] = 99] = "TD";
    FuelBuiltinElements[FuelBuiltinElements["TEXTAREA"] = 100] = "TEXTAREA";
    FuelBuiltinElements[FuelBuiltinElements["TFOOT"] = 101] = "TFOOT";
    FuelBuiltinElements[FuelBuiltinElements["TH"] = 102] = "TH";
    FuelBuiltinElements[FuelBuiltinElements["THEAD"] = 103] = "THEAD";
    FuelBuiltinElements[FuelBuiltinElements["TIME"] = 104] = "TIME";
    FuelBuiltinElements[FuelBuiltinElements["TITLE"] = 105] = "TITLE";
    FuelBuiltinElements[FuelBuiltinElements["TR"] = 106] = "TR";
    FuelBuiltinElements[FuelBuiltinElements["TRACK"] = 107] = "TRACK";
    FuelBuiltinElements[FuelBuiltinElements["U"] = 108] = "U";
    FuelBuiltinElements[FuelBuiltinElements["UL"] = 109] = "UL";
    FuelBuiltinElements[FuelBuiltinElements["VAR"] = 110] = "VAR";
    FuelBuiltinElements[FuelBuiltinElements["VIDEO"] = 111] = "VIDEO";
    FuelBuiltinElements[FuelBuiltinElements["WBR"] = 112] = "WBR";
    FuelBuiltinElements[FuelBuiltinElements["SYNTHETIC_TEXT"] = 113] = "SYNTHETIC_TEXT";
})(FuelBuiltinElements = exports.FuelBuiltinElements || (exports.FuelBuiltinElements = {}));
exports.CONVERSATION_TABLE = {
    className: 'class'
};
var Bytes;
(function (Bytes) {
    Bytes[Bytes["FUEL_ELEMENT_MARK"] = (Math.random() * 10000) << 1] = "FUEL_ELEMENT_MARK";
})(Bytes = exports.Bytes || (exports.Bytes = {}));
